[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "django-ez-tasks"
version = "0.1"
description = "A Django app for background task execution with multiple backends."
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "django>=6",
]
authors = [
    {name = "Alexander Hinze-Huettl", email = "hinze.alex@gmail.com"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
]

[project.urls]
Homepage = "https://github.com/al-eax/django_ez_tasks"
